//! Configuration and pure helpers for the `usta extract` workflow.
//!
//! `extract` is **deterministic**: same input + same config → same output,
//! byte for byte. The pure parts live here. The actual repo walking and
//! file I/O live in `usta-adapters` and `usta-app::extract`.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// User-controllable overrides loaded from `.usta-extract.toml` at the
/// source repo root, or supplied via the CLI.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ExtractConfig {
    /// Synthesized template id. Falls back to the source dir name.
    #[serde(default)]
    pub template_id: Option<String>,
    /// Display name for the synthesized template.
    #[serde(default)]
    pub template_display_name: Option<String>,
    /// Stacks to declare in the synthesized manifest (informational).
    #[serde(default)]
    pub stacks: Vec<String>,
    /// Globs of files to **always keep**, even if a default-noise rule
    /// would drop them.
    #[serde(default)]
    pub keep_paths: Vec<String>,
    /// Globs of files to **always drop**, even if they'd otherwise survive.
    #[serde(default)]
    pub drop_paths: Vec<String>,
    /// Literal substring → replacement. Applied to text files in
    /// longest-first order (longer keys first) so prefix overlaps don't
    /// clobber each other.
    #[serde(default)]
    pub identifiers: BTreeMap<String, String>,
    /// Optional manual partitioning into features. Files not matched by any
    /// partition stay in `base/`.
    #[serde(default)]
    pub features: Vec<FeaturePartition>,
}

/// One feature in the synthesized template — id + globs of files that
/// should be packed into `features/<id>/files/`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeaturePartition {
    /// Feature id (kebab-case).
    pub id: String,
    /// Display name in `usta list features`.
    #[serde(default)]
    pub display_name: Option<String>,
    /// Globs (relative to repo root) of files this feature owns.
    #[serde(default)]
    pub paths: Vec<String>,
    /// Whether this feature is selected by default at scaffold time.
    #[serde(default)]
    pub default: bool,
}

/// Default-drop globs — applied before user `keep_paths` / `drop_paths`,
/// in addition to anything `.gitignore` already excludes.
///
/// Returned as a sorted, stable list so tests can pin the set.
pub fn default_drop_globs() -> &'static [&'static str] {
    &[
        // Build artifacts and dependency caches
        "**/node_modules/**",
        "**/target/**",
        "**/dist/**",
        "**/build/**",
        "**/.next/**",
        "**/.nx/**",
        "**/.cache/**",
        "**/.expo/**",
        "**/.pnpm-store/**",
        "**/.uv-cache/**",
        // Python venvs and caches
        "**/.venv/**",
        "**/venv/**",
        "**/__pycache__/**",
        "**/.mypy_cache/**",
        "**/.ruff_cache/**",
        "**/.pytest_cache/**",
        // Lockfiles (regenerated by package managers)
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "**/yarn.lock",
        "**/uv.lock",
        "**/poetry.lock",
        "**/Cargo.lock",
        // Generated TS build info
        "**/*.tsbuildinfo",
        "**/*.tsbuildinfo.json",
        // Coverage / test outputs
        "**/coverage/**",
        "**/.coverage",
        "**/htmlcov/**",
        // OS / IDE noise
        "**/.DS_Store",
        "**/Thumbs.db",
        "**/.idea/**",
        "**/.vscode/**",
        // Local secrets / state
        "**/.env",
        "**/.env.local",
        "**/.env.*.local",
        // Git internals (defense-in-depth — `ignore` walker also handles)
        "**/.git/**",
        // Existing usta state from a previous extraction
        "**/.usta/**",
    ]
}

/// Apply identifier substitutions to text content. Substitutions are
/// applied in **longest-key-first** order so `MyExistingApp` is replaced before
/// `my-existing-app` (and similar prefix-sharing pairs don't clobber each other).
///
/// Pure. Same input → same output.
pub fn apply_identifier_substitutions(
    content: &str,
    identifiers: &BTreeMap<String, String>,
) -> String {
    if identifiers.is_empty() {
        return content.to_string();
    }
    let mut keys: Vec<&String> = identifiers.keys().collect();
    keys.sort_by(|a, b| b.len().cmp(&a.len()).then_with(|| a.cmp(b)));

    let mut out = content.to_string();
    for k in keys {
        if k.is_empty() {
            continue;
        }
        let v = &identifiers[k];
        out = out.replace(k.as_str(), v);
    }
    out
}

/// Heuristic: is this file content likely to be text we can sanitize?
///
/// Used to decide whether to apply identifier substitution. We don't try
/// to be clever — just skip files that contain a NUL byte in the first
/// 8 KiB.
pub fn looks_like_text(bytes: &[u8]) -> bool {
    let head = &bytes[..bytes.len().min(8192)];
    !head.contains(&0u8)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn substitutions_apply_longest_first() {
        let mut subs = BTreeMap::new();
        subs.insert("MyExistingApp".into(), "MyApp".into());
        subs.insert("my-existing-app".into(), "myapp".into());
        let out = apply_identifier_substitutions("MyExistingApp and my-existing-app", &subs);
        assert_eq!(out, "MyApp and myapp");
    }

    #[test]
    fn empty_substitutions_passthrough() {
        let out = apply_identifier_substitutions("hello", &BTreeMap::new());
        assert_eq!(out, "hello");
    }

    #[test]
    fn empty_key_is_ignored() {
        let mut subs = BTreeMap::new();
        subs.insert("".into(), "X".into());
        subs.insert("a".into(), "A".into());
        let out = apply_identifier_substitutions("abc", &subs);
        assert_eq!(out, "Abc");
    }

    #[test]
    fn looks_like_text_smoke() {
        assert!(looks_like_text(b"hello world"));
        assert!(looks_like_text(b""));
        assert!(!looks_like_text(b"hello\0world"));
    }

    #[test]
    fn default_drop_globs_includes_node_modules_and_git() {
        let globs = default_drop_globs();
        assert!(globs.iter().any(|g| g.contains("node_modules")));
        assert!(globs.iter().any(|g| g.contains(".git")));
        assert!(globs.iter().any(|g| g.contains("__pycache__")));
    }
}
